"use client";
import { useEffect, useMemo, useState } from "react";
import type { ChatMessage, Conversation, ProviderId } from "@/types/chat";
import { localConversationStore } from "@/lib/storage/local";

declare global { interface Window { google?: { accounts: { id: { initialize: (options: unknown) => void; prompt: () => void } } } } }

const quickActions = [
  ["💬", "Chat", "Talk to Rudy."], ["🎓", "Study", "Help me learn about: "], ["💻", "Coding", "Help me build: "],
  ["🔎", "Research", "Research this topic and give me a clear starting point: "], ["✍️", "Write", "Help me write: "], ["🧠", "Brainstorm", "Let's brainstorm ideas for: "],
];
const id = () => crypto.randomUUID();
const welcome: ChatMessage = { id: "welcome", role: "assistant", content: "Well, well, well... you're here.\n\nAlright. What's today's mission?", createdAt: Date.now() };

export default function RudyClient() {
  const [loggedIn, setLoggedIn] = useState(false), [name, setName] = useState("Adventurer"), [picture, setPicture] = useState(""), [theme, setTheme] = useState("dark");
  const [conversations, setConversations] = useState<Conversation[]>([]), [activeId, setActiveId] = useState<string | null>(null);
  const [draft, setDraft] = useState(""), [provider, setProvider] = useState<ProviderId>("gemini"), [thinking, setThinking] = useState(false), [sidebar, setSidebar] = useState(false), [settings, setSettings] = useState(false);
  useEffect(() => { setConversations(localConversationStore.get()); const saved = localStorage.getItem("rudy-profile-v1"); if (saved) { const profile = JSON.parse(saved); setLoggedIn(Boolean(profile.loggedIn)); setName(profile.name || "Adventurer"); setPicture(profile.picture || ""); } }, []);
  useEffect(() => { localConversationStore.save(conversations); }, [conversations]);
  useEffect(() => { document.documentElement.dataset.theme = theme; }, [theme]);
  const active = useMemo(() => conversations.find((c) => c.id === activeId), [conversations, activeId]);
  const messages = active?.messages || [welcome];
  const login = async (credential: string) => { const response = await fetch("/api/auth/google", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ credential }) }); const profile = await response.json(); if (!response.ok) throw new Error(profile.error); localStorage.setItem("rudy-profile-v1", JSON.stringify({ ...profile, loggedIn: true })); setName(profile.name); setPicture(profile.picture || ""); setLoggedIn(true); };
  const newChat = () => { const conversation = { id: id(), title: "New mission", messages: [welcome], updatedAt: Date.now() }; setConversations((c) => [conversation, ...c]); setActiveId(conversation.id); setSidebar(false); };
  const goHome = () => { setActiveId(null); setSidebar(false); };
  const updateConversation = (conversationId: string, messagesNext: ChatMessage[]) => setConversations((all) => all.map((c) => c.id === conversationId ? { ...c, messages: messagesNext, title: c.messages.length <= 1 ? messagesNext.at(-1)?.content.slice(0, 34) || "New mission" : c.title, updatedAt: Date.now() } : c));
  const send = async (text = draft) => { if (!text.trim() || thinking) return; let conversationId = activeId; if (!conversationId) { const created = { id: id(), title: text.slice(0, 34), messages: [welcome], updatedAt: Date.now() }; setConversations((c) => [created, ...c]); setActiveId(created.id); conversationId = created.id; }
    const user: ChatMessage = { id: id(), role: "user", content: text.trim(), createdAt: Date.now() }; const prior = (conversations.find((c) => c.id === conversationId)?.messages || [welcome]); const next = [...prior, user]; updateConversation(conversationId, next); setDraft(""); setThinking(true);
    try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ messages: next, provider }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); updateConversation(conversationId, [...next, { id: id(), role: "assistant", content: data.content, createdAt: Date.now() }]); }
    catch (error) { updateConversation(conversationId, [...next, { id: id(), role: "assistant", content: error instanceof Error ? error.message : "The trail got foggy. Please retry.", createdAt: Date.now() }]); } finally { setThinking(false); }
  };
  if (!loggedIn) return <Landing login={login} />;
  return <main className="app-shell"><aside className={`sidebar ${sidebar ? "open" : ""}`}><div className="brand"><button className="brand-button" onClick={goHome}><img className="brand-logo" src="/logo-64.png" width={28} height={28} alt="Rudy logo" /> RUDY</button><button className="icon mobile-only" onClick={() => setSidebar(false)}>×</button></div><button className="new-chat" onClick={newChat}>＋ New chat</button><button className="nav-item">⌕ <span>Search conversations</span></button><p className="side-label">RECENT EXPEDITIONS</p><div className="chat-list">{conversations.length ? conversations.map((c) => <button className={`chat-link ${c.id === activeId ? "selected" : ""}`} onClick={() => { setActiveId(c.id); setSidebar(false); }} key={c.id}>◌ {c.title}<span onClick={(event) => { event.stopPropagation(); setConversations((list) => list.filter((x) => x.id !== c.id)); if (activeId === c.id) setActiveId(null); }}>×</span></button>) : <p className="muted">No trails yet.</p>}</div><div className="sidebar-bottom"><button className="nav-item" onClick={() => setSettings(true)}>⚙ Settings</button><button className="account" onClick={() => setSettings(true)}>{picture ? <img className="avatar-image" src={picture} alt=""/> : <span className="avatar">{name[0]}</span>}<span><b>{name}</b><small>Google account</small></span></button></div></aside><section className="workspace"><header><button className="icon mobile-only" onClick={() => setSidebar(true)}>☰</button><button className="brand mobile-brand" onClick={goHome}><img className="brand-logo" src="/logo-64.png" width={24} height={24} alt="Rudy logo" /> RUDY</button><span className="online"><i /> Online</span></header><div className="content">{!activeId ? <Home name={name} onAction={(value) => { setDraft(value); }} /> : <Chat messages={messages} thinking={thinking} onRetry={() => send(messages.filter((m) => m.role === "user").at(-1)?.content || "")} />}</div><Composer draft={draft} setDraft={setDraft} send={send} thinking={thinking} /></section>{settings && <Settings name={name} setName={setName} theme={theme} setTheme={setTheme} close={() => setSettings(false)} signOut={() => { localStorage.removeItem("rudy-profile-v1"); setLoggedIn(false); }} clear={() => { localConversationStore.clear(); setConversations([]); setActiveId(null); }} />}</main>;
}

function Landing({ login }: { login: (credential: string) => Promise<void> }) { const [error, setError] = useState(""), [clientId, setClientId] = useState(""); useEffect(() => { fetch("/api/auth/google/config").then(async (response) => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setClientId(data.clientId); }).catch((err: Error) => setError(err.message)); }, []); useEffect(() => { if (!clientId) return; const script = document.createElement("script"); script.src = "https://accounts.google.com/gsi/client"; script.async = true; script.onload = () => window.google?.accounts.id.initialize({ client_id: clientId, callback: async ({ credential }: { credential: string }) => { try { await login(credential); } catch (err) { setError(err instanceof Error ? err.message : "Google sign-in failed."); } } }); document.head.appendChild(script); return () => script.remove(); }, [clientId, login]); const beginGoogle = () => { if (!clientId) { setError(error || "Google sign-in is still loading. Try again in a moment."); return; } if (!window.google) { setError("Google sign-in is still loading. Try again in a moment."); return; } window.google.accounts.id.prompt(); }; return <main className="landing"><nav className="landing-nav"><div className="brand"><img className="brand-logo" src="/logo-64.png" width={28} height={28} alt="Rudy logo" /> RUDY</div><span>Prototype V1</span></nav><div className="hero"><div><p className="eyebrow">YOUR NEXT EXPEDITION STARTS HERE</p><h1>Your AI<br/><em>adventure</em><br/>companion.</h1><p className="lead">One conversation. Multiple AI capabilities. One Rudy.</p><div className="hero-actions"><div className="google-row"><img className="brand-logo-sm" src="/logo-64.png" width={40} height={40} alt="Rudy logo" /><button className="google" onClick={beginGoogle}><span>G</span> Continue with Google</button></div><a href="#meet">Meet Rudy <b>↓</b></a></div>{error && <p className="auth-error" role="alert">{error}</p>}</div><div className="rudy-orb" aria-label="An original adventurous AI creature"><div className="map-line line-one"/><div className="map-line line-two"/><div className="creature"><span className="ear left"/><span className="ear right"/><span className="eye">●</span><span className="eye closed">—</span><span className="smile">⌣</span></div><p>CURIOUS. CLEVER. READY.</p></div></div><section id="meet" className="meet"><p>Not another polite little chatbot.</p><h2>Rudy is here to help you<br/>move the <em>mission</em> forward.</h2></section></main> }
function Home({ name, onAction }: { name: string; onAction: (text: string) => void }) { return <div className="home"><p className="greeting">Good evening, {name}.</p><h2>What&apos;s today&apos;s mission?</h2><div className="actions">{quickActions.map(([icon, title, prompt]) => <button onClick={() => onAction(prompt)} key={title}><span>{icon}</span><b>{title}</b><small>{title === "Chat" ? prompt : ` ${prompt}`}</small><i>→</i></button>)}</div><p className="hint">Choose a starting point, or ask Rudy anything below.</p></div> }
function Linkified({ line }: { line: string }) { return <>{line.split(/(https?:\/\/[^\s]+)/g).map((part, index) => part.match(/^https?:\/\//) ? <a href={part} target="_blank" rel="noopener noreferrer" key={index}>{part}</a> : part)}</>; }
function Chat({ messages, thinking, onRetry }: { messages: ChatMessage[]; thinking: boolean; onRetry: () => void }) { return <div className="messages" aria-live="polite">{messages.map((message) => <article key={message.id} className={`message ${message.role}`}><div className="message-mark">{message.role === "assistant" ? "🦦" : "YOU"}</div><div><div className="bubble">{message.content.split("\n").map((line, i) => <p key={i}>{line ? <Linkified line={line} /> : " "}</p>)}</div>{message.role === "assistant" && message.id !== "welcome" && <div className="message-tools"><button onClick={() => navigator.clipboard.writeText(message.content)}>Copy</button><button onClick={onRetry}>Regenerate</button></div>}</div></article>)}{thinking && <article className="message assistant" role="status" aria-label="Waiting for the fastest AI provider"><div className="message-mark">🦦</div><div className="typing"><span>Rudy is waiting for the fastest provider</span><i/><i/><i/></div></article>}</div> }
function Composer({ draft, setDraft, send, thinking }: { draft: string; setDraft: (value: string) => void; send: () => void; thinking: boolean }) { return <div className="composer-wrap"><div className="composer"><button className="icon" aria-label="Attach a file">＋</button><textarea value={draft} onChange={(e) => setDraft(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); } }} placeholder="Ask Rudy anything..." rows={1}/><button className="icon" aria-label="Voice input">◉</button><button className="send" onClick={() => send()} disabled={!draft.trim() || thinking} aria-label="Send message">↑</button></div><p>Rudy can make mistakes. Always check important details.</p></div> }
function Settings({ name, setName, theme, setTheme, close, signOut, clear }: { name: string; setName: (value: string) => void; theme: string; setTheme: (value: string) => void; close: () => void; signOut: () => void; clear: () => void }) { return <div className="modal-backdrop" role="presentation"><section className="settings" role="dialog" aria-modal="true" aria-label="Settings"><header><div><p className="eyebrow">BASE CAMP</p><h2>Settings</h2></div><button className="icon" onClick={close}>×</button></header><div className="settings-body"><section><h3>Account</h3><label>Name<input value={name} onChange={(e) => setName(e.target.value)} /></label><button className="signout-button" onClick={signOut}>⎋ Sign out</button></section><section><h3>Rudy</h3><label>Response style<select defaultValue="balanced"><option>Concise</option><option value="balanced">Balanced</option><option>Detailed</option></select></label><label>Humor level<input type="range" defaultValue="45" /></label></section><section><h3>Appearance</h3><div className="segmented">{["light", "dark", "system"].map((value) => <button className={theme === value ? "active" : ""} onClick={() => setTheme(value)} key={value}>{value}</button>)}</div></section><section><h3>Privacy</h3><button className="danger" onClick={clear}>Clear local conversations</button></section></div></section></div> }
